name: Build and Test GLFW

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Install GLFW dependencies
        run: |
          sudo apt-get install -y \
            libxkbcommon-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libglfw3-dev \
            libx11-dev

      - name: Clone and build GLFW
        run: |
          cd ${{ github.workspace }}
          git clone --branch master https://github.com/glfw/glfw.git glfw_build
          cd glfw_build
          mkdir build
          mkdir install
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/glfw_build/install
          cmake --build .
          sudo cmake --build . --target install --config Release

      - name: Setup Vulkan
        uses: NcStudios/VulkanCI@v1.0
        with:
          sdkVersion: 1.3.283.0
          installPath: ${{ github.workspace }}

      - name: Setup GLM
        run: |
          cd ${{ github.workspace }}
          git clone --branch master https://github.com/g-truc/glm.git glm

      - name: Build app
        run: |
          cd ${{ github.workspace }}/code/finished-projects/sierpinski-triangle
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH="${{ github.workspace }}/glfw_build/install/lib/cmake/glfw3" -DGLM_PATH=${{ github.workspace }}/glm
          cmake --build .